export enum AppStorageMap {
  // 选中常用地址
  SELECTED_ADDRESS = 'SelectedAddress',
}

export enum RouterMap {
  // 关联账号页
  BIND_PHONE = 'BindPhonePage',
  // 查询订单页
  QUERY_PAGE = 'QueryPage',
  // 缴费订单页
  PAY_PAGE = 'PayPage',
  // 新增车牌页
  ADD_LICENSE = 'AddLicense',
  // 我的车牌页
  MY_LICENSE = 'MyLicense',
  // 常用地址页
  COMMON_ADDRESS = 'CommonAddress',
  // 搜索列表页
  SEARCH_LIST = 'SearchList',
  // 停车场详情
  SITE_DETAIL = 'SiteDetail',
  // 订单列表页
  ORDER_LIST = 'OrderList',
  // 订单详情页
  ORDER_DETAIL = 'OrderDetail',
  // 我的收藏页
  MY_COLLECT = 'MyCollect',
  // 信息修改页
  PROFILE_EDIT = 'ProfileEdit',
  // 隐私政策页
  PRIVACY_POLICY = 'PrivacyPolicy',
}