/*
 * Copyright (c) 2024 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

export { MinePageBuilder } from './src/main/ets/views/MinePage';

export { EditPersonalCenterBuilder } from './src/main/ets/views/EditPersonalCenterPage';

export { SetupPageBuilder } from './src/main/ets/views/SetupPage';

export { FeedbackPageBuilder } from './src/main/ets/views/FeedbackPage';

export { PracticeRecordsPageBuilder } from './src/main/ets/views/PracticeRecordsPage';

export { PracticeDetailsPageBuilder } from './src/main/ets/views/PracticeDetailsPage';

export { OneDayPracticeRecordsPageBuilder } from './src/main/ets/views/OneDayPracticeRecordsPage';

export { BrowsingHistoryPageBuilder } from './src/main/ets/views/BrowsingHistoryPage';

export { MyOrderPageBuilder } from './src/main/ets/views/MyOrderPage';

export { OrderDetailPageBuilder } from './src/main/ets/views/OrderDetailPage';

export { PrivacyStatementPageBuilder } from './src/main/ets/views/PrivacyStatementPage';

export { PrivacyAgreementPageBuilder, DialogPageBuilder } from './src/main/ets/views/PrivacyAgreementPage';

export { MessageCenterPageBuilder } from './src/main/ets/views/MessageCenterPage';

export { FeedbackRecordPageBuilder } from './src/main/ets/views/FeedbackRecordPage';

export { AboutPageBuilder } from './src/main/ets/views/AboutPage';

export { CollectionPageBuilder } from './src/main/ets/views/CollectionPage';

export { CoursePageBuilder } from './src/main/ets/views/CoursePage';


