export { MinePage } from './src/main/ets/pages/MinePage';

export { PersonalInfo } from './src/main/ets/pages/PersonalInfo';

export { RealNameAuth } from './src/main/ets/pages/RealNameAuth';

export { TripDetail } from './src/main/ets/pages/TripDetail';

export { BackID } from './src/main/ets/pages/BackID';

export { FrontID } from './src/main/ets/pages/FrontID';

export { CycleRecordPage } from './src/main/ets/pages/CycleRecordPage';

export { LoginWithHuaweiIDComponent } from './src/main/ets/pages/LoginWithHuaweiIDComponent';

export { SettingPage } from './src/main/ets/pages/SettingPage';

export { PrivacyPolicyPage } from './src/main/ets/pages/PrivacyPolicyPage';

export { DataCollectionPage } from './src/main/ets/pages/DataCollectionPage';

export { DataSharingPage } from './src/main/ets/pages/DataSharingPage';

export { UserAgreementPage} from './src/main/ets/pages/UserAgreementPage';

export { CycleRecordDatas, CycleRecordData  } from './src/main/ets/mockData/CycleRecordData'