export class CommonConstants {
  /**
   * Constant for screen dpi.
   */
  static readonly SCREEN_DPI_CONSTANT: number = 160;
  /**
   * Full width.
   */
  static readonly FULL_WIDTH: string = '100%';
  /**
   * Full height.
   */
  static readonly FULL_HEIGHT: string = '100%';
  /**
   * Column lower height.
   */
  static readonly HEIGHT_LOW: number = 150;
  /**
   * Column middle height.
   */
  static readonly HEIGHT_MIDDLE: number = 369;
  /**
   * Column higher height of md.
   */
  static readonly HEIGHT_MD: number = 599;
  /**
   * Column margin left of md.
   */
  static readonly LEFT_MD: number = 24;
  /**
   * Change position line.
   */
  static readonly CHANGE: number = 200;
  /**
   * Column margin right of md.
   */
  static readonly RIGHT_MD: number = 350;
}