export { HomePage as NewHomePage } from './src/main/ets/pages/HomePage';

export { CustomScanPage } from './src/main/ets/pages/CustomScanPage';

export { FaultReportingPage } from './src/main/ets/views/FaultReportingPage';

export { FeedbackPage } from './src/main/ets/views/FeedbackPage';

export { UserGuidePage } from './src/main/ets/views/UserGuidePage';

export { ManualInput } from './src/main/ets/pages/ManualInput';

export { Cycling } from './src/main/ets/pages/Cycling';
