/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2023. All rights reserved.
 * Generated by the CloudDB ObjectType compiler. DO NOT EDIT!
 */

class CloudUserCourseInfo {
    id: string;
    courseId: number;
    userId: string;
    type: number;
    name: string;
    summary: string;
    detail: string;
    mainDiagram: string;
    price: number;
    expireType: number;
    startTime: string;
    endTime: string;
    orderTime: string;
    classHour: number;
    status: number;
    currentHour: number;
    timetable: string;

    constructor() {
    }

    getFieldTypeMap():  Map<string, string> {
        let fieldTypeMap = new Map<string, string>();
        fieldTypeMap.set('id', 'String');
        fieldTypeMap.set('courseId', 'Integer');
        fieldTypeMap.set('userId', 'String');
        fieldTypeMap.set('type', 'Integer');
        fieldTypeMap.set('name', 'String');
        fieldTypeMap.set('summary', 'String');
        fieldTypeMap.set('detail', 'Text');
        fieldTypeMap.set('mainDiagram', 'String');
        fieldTypeMap.set('price', 'Float');
        fieldTypeMap.set('expireType', 'Integer');
        fieldTypeMap.set('startTime', 'String');
        fieldTypeMap.set('endTime', 'String');
        fieldTypeMap.set('orderTime', 'String');
        fieldTypeMap.set('classHour', 'Integer');
        fieldTypeMap.set('status', 'Integer');
        fieldTypeMap.set('currentHour', 'Integer');
        fieldTypeMap.set('timetable', 'String');
        return fieldTypeMap;
    }

    getClassName(): string {
        return 'CloudUserCourseInfo';
    }

    getPrimaryKeyList(): string[] {
        let primaryKeyList: string[] = [];
        primaryKeyList.push('id');
        return primaryKeyList;
    }

    getIndexList(): string[] {
        let indexList: string[] = [];
        return indexList;
    }

    getEncryptedFieldList(): string[] {
        let encryptedFieldList: string[] = [];
        return encryptedFieldList;
    }

    setId(id: string): void {
        this.id = id;
    }

    getId(): string  {
        return this.id;
    }

    setCourseId(courseId: number): void {
        this.courseId = courseId;
    }

    getCourseId(): number  {
        return this.courseId;
    }

    setUserId(userId: string): void {
        this.userId = userId;
    }

    getUserId(): string  {
        return this.userId;
    }

    setType(type: number): void {
        this.type = type;
    }

    getType(): number  {
        return this.type;
    }

    setName(name: string): void {
        this.name = name;
    }

    getName(): string  {
        return this.name;
    }

    setSummary(summary: string): void {
        this.summary = summary;
    }

    getSummary(): string  {
        return this.summary;
    }

    setDetail(detail: string): void {
        this.detail = detail;
    }

    getDetail(): string  {
        return this.detail;
    }

    setMainDiagram(mainDiagram: string): void {
        this.mainDiagram = mainDiagram;
    }

    getMainDiagram(): string  {
        return this.mainDiagram;
    }

    setPrice(price: number): void {
        this.price = price;
    }

    getPrice(): number  {
        return this.price;
    }

    setExpireType(expireType: number): void {
        this.expireType = expireType;
    }

    getExpireType(): number  {
        return this.expireType;
    }

    setStartTime(startTime: string): void {
        this.startTime = startTime;
    }

    getStartTime(): string  {
        return this.startTime;
    }

    setEndTime(endTime: string): void {
        this.endTime = endTime;
    }

    getEndTime(): string  {
        return this.endTime;
    }

    setOrderTime(orderTime: string): void {
        this.orderTime = orderTime;
    }

    getOrderTime(): string  {
        return this.orderTime;
    }

    setClassHour(classHour: number): void {
        this.classHour = classHour;
    }

    getClassHour(): number  {
        return this.classHour;
    }

    setStatus(status: number): void {
        this.status = status;
    }

    getStatus(): number  {
        return this.status;
    }

    setCurrentHour(currentHour: number): void {
        this.currentHour = currentHour;
    }

    getCurrentHour(): number  {
        return this.currentHour;
    }

    setTimetable(timetable: string): void {
        this.timetable = timetable;
    }

    getTimetable(): string  {
        return this.timetable;
    }

    static parseFrom(inputObject: any): CloudUserCourseInfo {
        let result = new CloudUserCourseInfo();
        if (!inputObject) {
            return result;
        }
        if (inputObject.id) {
            result.id = inputObject.id;
        }
        if (inputObject.courseId) {
            result.courseId = inputObject.courseId;
        }
        if (inputObject.userId) {
            result.userId = inputObject.userId;
        }
        if (inputObject.type) {
            result.type = inputObject.type;
        }
        if (inputObject.name) {
            result.name = inputObject.name;
        }
        if (inputObject.summary) {
            result.summary = inputObject.summary;
        }
        if (inputObject.detail) {
            result.detail = inputObject.detail;
        }
        if (inputObject.mainDiagram) {
            result.mainDiagram = inputObject.mainDiagram;
        }
        if (inputObject.price) {
            result.price = inputObject.price;
        }
        if (inputObject.expireType) {
            result.expireType = inputObject.expireType;
        }
        if (inputObject.startTime) {
            result.startTime = inputObject.startTime;
        }
        if (inputObject.endTime) {
            result.endTime = inputObject.endTime;
        }
        if (inputObject.orderTime) {
            result.orderTime = inputObject.orderTime;
        }
        if (inputObject.classHour) {
            result.classHour = inputObject.classHour;
        }
        if (inputObject.status) {
            result.status = inputObject.status;
        }
        if (inputObject.currentHour) {
            result.currentHour = inputObject.currentHour;
        }
        if (inputObject.timetable) {
            result.timetable = inputObject.timetable;
        }
        return result;
    }
}

export { CloudUserCourseInfo };