/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2023. All rights reserved.
 * Generated by the CloudDB ObjectType compiler. DO NOT EDIT!
 */

class OrderInfo {
    orderNo: string;
    userId: string;
    orderTime: Date;
    orderStatus: number;
    paymentMethod: number;
    totalPrice: number;
    orderStr: string;
    student: string;
    phone: string;
    remark: string;
    courseInfo: string;
    expireTime: Date;

    constructor() {
    }

    getFieldTypeMap():  Map<string, string> {
        let fieldTypeMap = new Map<string, string>();
        fieldTypeMap.set('orderNo', 'String');
        fieldTypeMap.set('userId', 'String');
        fieldTypeMap.set('orderTime', 'Date');
        fieldTypeMap.set('orderStatus', 'Integer');
        fieldTypeMap.set('paymentMethod', 'Integer');
        fieldTypeMap.set('totalPrice', 'Float');
        fieldTypeMap.set('orderStr', 'String');
        fieldTypeMap.set('student', 'String');
        fieldTypeMap.set('phone', 'String');
        fieldTypeMap.set('remark', 'String');
        fieldTypeMap.set('courseInfo', 'Text');
        fieldTypeMap.set('expireTime', 'Date');
        return fieldTypeMap;
    }

    getClassName(): string {
        return 'OrderInfo';
    }

    getPrimaryKeyList(): string[] {
        let primaryKeyList: string[] = [];
        primaryKeyList.push('orderNo');
        return primaryKeyList;
    }

    getIndexList(): string[] {
        let indexList: string[] = [];
        return indexList;
    }

    getEncryptedFieldList(): string[] {
        let encryptedFieldList: string[] = [];
        return encryptedFieldList;
    }

    setOrderNo(orderNo: string): void {
        this.orderNo = orderNo;
    }

    getOrderNo(): string  {
        return this.orderNo;
    }

    setUserId(userId: string): void {
        this.userId = userId;
    }

    getUserId(): string  {
        return this.userId;
    }

    setOrderTime(orderTime: Date): void {
        this.orderTime = orderTime;
    }

    getOrderTime(): Date  {
        return this.orderTime;
    }

    setOrderStatus(orderStatus: number): void {
        this.orderStatus = orderStatus;
    }

    getOrderStatus(): number  {
        return this.orderStatus;
    }

    setPaymentMethod(paymentMethod: number): void {
        this.paymentMethod = paymentMethod;
    }

    getPaymentMethod(): number  {
        return this.paymentMethod;
    }

    setTotalPrice(totalPrice: number): void {
        this.totalPrice = totalPrice;
    }

    getTotalPrice(): number  {
        return this.totalPrice;
    }

    setOrderStr(orderStr: string): void {
        this.orderStr = orderStr;
    }

    getOrderStr(): string  {
        return this.orderStr;
    }

    setStudent(student: string): void {
        this.student = student;
    }

    getStudent(): string  {
        return this.student;
    }

    setPhone(phone: string): void {
        this.phone = phone;
    }

    getPhone(): string  {
        return this.phone;
    }

    setRemark(remark: string): void {
        this.remark = remark;
    }

    getRemark(): string  {
        return this.remark;
    }

    setCourseInfo(courseInfo: string): void {
        this.courseInfo = courseInfo;
    }

    getCourseInfo(): string  {
        return this.courseInfo;
    }

    setExpireTime(expireTime: Date): void {
        this.expireTime = expireTime;
    }

    getExpireTime(): Date  {
        return this.expireTime;
    }

    static parseFrom(inputObject: any): OrderInfo {
        let result = new OrderInfo();
        if (!inputObject) {
            return result;
        }
        if (inputObject.orderNo) {
            result.orderNo = inputObject.orderNo;
        }
        if (inputObject.userId) {
            result.userId = inputObject.userId;
        }
        if (inputObject.orderTime) {
            result.orderTime = new Date(inputObject.orderTime);
        }
        if (inputObject.orderStatus) {
            result.orderStatus = inputObject.orderStatus;
        }
        if (inputObject.paymentMethod) {
            result.paymentMethod = inputObject.paymentMethod;
        }
        if (inputObject.totalPrice) {
            result.totalPrice = inputObject.totalPrice;
        }
        if (inputObject.orderStr) {
            result.orderStr = inputObject.orderStr;
        }
        if (inputObject.student) {
            result.student = inputObject.student;
        }
        if (inputObject.phone) {
            result.phone = inputObject.phone;
        }
        if (inputObject.remark) {
            result.remark = inputObject.remark;
        }
        if (inputObject.courseInfo) {
            result.courseInfo = inputObject.courseInfo;
        }
        if (inputObject.expireTime) {
            result.expireTime = new Date(inputObject.expireTime);
        }
        return result;
    }
}

export { OrderInfo };