/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2024-2024. All rights reserved.
 * Generated by the CloudDB ObjectType compiler. DO NOT EDIT!
 */
import { cloudDatabase } from '@kit.CloudFoundationKit';

class CloudCheckInRecord extends cloudDatabase.DatabaseObject {
  public userId: string;
  public taskId: number;
  public activityId: number;
  public textDetail: string;
  public pictureDetail: string;
  public audioDetail: string;
  public videoDetail: string;
  public createTime: Date;
  public recordId: string;

  public naturalbase_ClassName(): string {
    return 'CloudCheckInRecord';
  }
}

export { CloudCheckInRecord };
