/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2024-2024. All rights reserved.
 * Generated by the CloudDB ObjectType compiler. DO NOT EDIT!
 */
import { cloudDatabase } from '@kit.CloudFoundationKit';

class CloudCourseInfo extends cloudDatabase.DatabaseObject {
  public courseId: number;
  public type: number;
  public name: string;
  public summary: string;
  public detail: string;
  public mainDiagram: string;
  public price: number;
  public expireType: number;
  public startTime: string;
  public endTime: string;
  public orderTime: string;
  public classHour: number;
  public status: number;
  public currentHour: number;
  public timetable: string;

  public naturalbase_ClassName(): string {
    return 'CloudCourseInfo';
  }
}

export { CloudCourseInfo };
