/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2024-2024. All rights reserved.
 * Generated by the CloudDB ObjectType compiler. DO NOT EDIT!
 */
import { cloudDatabase } from '@kit.CloudFoundationKit';

class CloudCheckInActivity extends cloudDatabase.DatabaseObject {
  public activityId: number;
  public name: string;
  public summary: string;
  public detail: string;
  public mainDiagram: string;
  public price: number;
  public requirement: string;
  public participationCount: number;
  public historyCount: number;
  public taskDirectory: string;

  public naturalbase_ClassName(): string {
    return 'CloudCheckInActivity';
  }
}

export { CloudCheckInActivity };
